// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:bf56abbe-8545-46e0-b707-a97325139afb",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_6FBSf1MNR",
    "aws_user_pools_web_client_id": "2tqpr1dmsnsqsgqgon90i14fsj"
};


export default awsmobile;
